on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run lint (optional)
      run: |
        # Example of linting (optional step if you have a linter)
        # npm run lint

    - name: Build project (optional)
      run: |
        # Optional build step if you have a build process
        # npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust this if your HTML, CSS, JS files are in a subfolder
